// Re-export barrel for the `/info` response type modules, split by domain:
//   core.ts      — node / account / market / vault / staking / fee shapes
//   reads.ts     — book / trade / funding / candle / account-history reads
//   hl-parity.ts — the node-snapshot parity query shapes
//   account-overview.ts — the account's non-trading state, in one read
//   bridge.ts    — the custody-bridge deployment + withdrawal-outbox reads

export type {
  NodeInfo,
  AccountState,
  AccountPosition,
  DexPositions,
  TokenBalance,
  Tier,
  MarginMode,
  Abstraction,
  MarketStatic,
  MarketDynamic,
  MarketKind,
  MarginTier,
  TokenEvmContract,
  PerpUnderlyingToken,
  Funding,
  VaultState,
  StakingState,
  Delegation,
  PendingUnstake,
  RewardPool,
  RiskOverride,
  FeeSchedule,
  FeeTier,
  SpotMarginState,
  SpotMarginAccount,
  SpotMarginParams,
  EarnState,
  EarnPool,
  EncodeAction,
} from './core.js';
export type {
  TradeSide,
  OrderTif,
  OrderTrigger,
  OpenOrders,
  OpenOrder,
  L2Book,
  L2BookParams,
  L2Level,
  Trades,
  TradeRecord,
  UserFills,
  UserPositionHistory,
  PositionHistoryRow,
  UserFill,
  FundingHistory,
  FundingSample,
  Candle,
  CandleType,
  CandleSnapshot,
  BlockInfo,
  AgentEntry,
  SubAccountEntry,
  Mip3ActiveBids,
  Mip3Bid,
  OrderStatusInfo,
  RestingOrderStatus,
  TriggerOrderStatus,
  HistoricalOrders,
  HistoricalOrder,
  UserFunding,
  UserFundingRecord,
  UserLedgerUpdates,
  UserNonFundingLedgerUpdates,
  LedgerUpdate,
} from './reads.js';
export type {
  Markets,
  MarketsMeta,
  SpotMeta,
  SpotPair,
  SpotToken,
  ExchangeStatus,
  ActiveAssetData,
  VaultSummaries,
  VaultSummary,
  VaultEquity,
  UserRateLimit,
  SpotDeployAuction,
  DelegatorSummary,
  ValidatorL1Votes,
  ValidatorL1Vote,
  PerpDexs,
  PerpDex,
  PerpDexLimits,
  PerpDexPerMarketLimits,
  ValidatorSummaries,
  ValidatorSummary,
  GossipRootIps,
  AdvertisedPeer,
} from './hl-parity.js';
export type {
  AccountOverview,
  AccountOverviewStaking,
  AccountOverviewVault,
  AccountRole,
} from './account-overview.js';
export type {
  BridgeChainConfigRow,
  BridgeOutboxEntry,
  BridgeOutboxStatus,
  BridgeScanPolicy,
  BridgeUserOutbox,
} from './bridge.js';
