// Re-export barrel for the `/info` response type modules, split by domain:
//   core.ts      — node / account / market / vault / staking / fee shapes
//   reads.ts     — book / trade / account-history reads
//   hl-parity.ts — the HL-node parity query shapes

export type {
  NodeInfo,
  AccountState,
  AccountPosition,
  Balances,
  Tier,
  MarginMode,
  MarketInfo,
  MarketKind,
  Funding,
  VaultState,
  StakingState,
  Delegation,
  PendingUnstake,
  FeeSchedule,
  FeeTier,
} from './core.js';
export type {
  OpenOrders,
  OpenOrder,
  L2Book,
  L2Level,
  RecentTrades,
  UserFills,
  FundingHistory,
  FundingSample,
  Candle,
  BlockInfo,
  Agents,
  AgentEntry,
  SubAccounts,
  SubAccountEntry,
  Mip3ActiveBids,
  Mip3Bid,
} from './reads.js';
export type {
  SpotMeta,
  SpotPair,
  SpotToken,
  SpotClearinghouseState,
  SpotBalance,
  ExchangeStatus,
  FrontendOpenOrders,
  FrontendOpenOrder,
  OrderTrigger,
  Liquidatable,
  LiquidatableAccount,
  ActiveAssetData,
  MaxMarketOrderNtls,
  MaxMarketOrderNtl,
  VaultSummaries,
  VaultSummary,
  UserVaultEquities,
  VaultEquity,
  LeadingVaults,
  UserRateLimit,
  SpotDeployState,
  DelegatorSummary,
  MaxBuilderFee,
  UserToMultiSigSigners,
  UserRole,
  PerpsAtOpenInterestCap,
  ValidatorL1Votes,
  ValidatorL1Vote,
  MarginTable,
  MarginTier,
  PerpDexs,
  PerpDex,
  ValidatorSummaries,
  ValidatorSummary,
  GossipRootIps,
  WebData2,
  WebData2Clearinghouse,
  WebData2Position,
} from './hl-parity.js';
