// Re-export barrel for the `/info` response type modules, split by domain:
//   core.ts      — node / account / market / vault / staking / fee shapes
//   reads.ts     — book / trade / funding / candle / account-history reads
//   hl-parity.ts — the node-snapshot parity query shapes
//   web-data.ts  — the consolidated `web_data` account snapshot

export type {
  NodeInfo,
  AccountState,
  AccountPosition,
  DexPositions,
  TokenBalance,
  Tier,
  MarginMode,
  Abstraction,
  MarketInfo,
  MarketStatic,
  MarketDynamic,
  MarketKind,
  MarginTier,
  TokenEvmContract,
  PerpUnderlyingToken,
  Funding,
  VaultState,
  StakingState,
  Delegation,
  PendingUnstake,
  FeeSchedule,
  FeeTier,
  SpotMarginState,
  SpotMarginAccount,
  SpotMarginParams,
  EarnState,
  EarnPool,
  PmSummary,
  EncodeAction,
} from './core.js';
export type {
  TradeSide,
  OrderTif,
  OrderTrigger,
  OpenOrders,
  OpenOrder,
  L2Book,
  L2BookParams,
  L2Level,
  RecentTrades,
  TradesByTime,
  TradeRecord,
  UserFills,
  UserFillsByTime,
  UserPositionHistory,
  PositionHistoryRow,
  UserFill,
  FundingHistory,
  FundingSample,
  PredictedFunding,
  Candle,
  CandleType,
  CandleSnapshot,
  BlockInfo,
  Agents,
  AgentEntry,
  SubAccounts,
  SubAccountEntry,
  Mip3ActiveBids,
  Mip3Bid,
  OrderStatusInfo,
  RestingOrderStatus,
  TriggerOrderStatus,
  HistoricalOrders,
  HistoricalOrder,
  UserFunding,
  UserFundingRecord,
  UserLedgerUpdates,
  UserNonFundingLedgerUpdates,
  LedgerUpdate,
} from './reads.js';
export type {
  Markets,
  MarketsMeta,
  SpotMeta,
  SpotPair,
  SpotToken,
  SpotClearinghouseState,
  SpotBalance,
  ExchangeStatus,
  Liquidatable,
  LiquidatableAccount,
  ActiveAssetData,
  MaxMarketOrderNtls,
  MaxMarketOrderNtl,
  VaultSummaries,
  VaultSummary,
  UserVaultEquities,
  VaultEquity,
  LeadingVaults,
  UserRateLimit,
  SpotDeployState,
  DelegatorSummary,
  MaxBuilderFee,
  UserToMultiSigSigners,
  UserRole,
  PerpsAtOpenInterestCap,
  ValidatorL1Votes,
  ValidatorL1Vote,
  PerpDexs,
  PerpDex,
  ValidatorSummaries,
  ValidatorSummary,
  GossipRootIps,
} from './hl-parity.js';
export type { WebData, WebDataStaking, WebDataVault } from './web-data.js';
