// Multi-sig inner-signature signing — chain-pinned known-answer vectors.
//
// The inner digest is what each roster member signs; it MUST match the chain
// verifier byte-for-byte or the acting bundle is rejected. Two schemes:
//   - user-bound (`MetaFluxMultiSigInner(address user,string action,uint64 nonce)`)
//     — the scheme in force after the scheduled network upgrade;
//   - legacy (`MetaFluxAction(string action,uint64 nonce)`) — the pre-upgrade one.
//
// Fixtures generated by executing the chain crate `core-state` (chain id 114514,
// user 0x2222…22, inner blob = ASCII `{"type":"noop","params":{}}`, nonce
// 1735689600000). Also pins the outer `multi_sig` typed-wrapper encodeType.

import { describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgDir = resolve(__dirname, '..', 'pkg');
const wasmBuilt = existsSync(resolve(pkgDir, 'metaflux_client_wasm.js'));

if (!wasmBuilt) {
  console.warn(
    '[multisig.test.ts] pkg/ not found — skipping WASM tests. ' +
      'Run `npm run build:wasm` to enable.',
  );
}

const CHAIN_ID = 114514;
const USER = '0x2222222222222222222222222222222222222222';
const NONCE = 1_735_689_600_000n;
const BLOB = new TextEncoder().encode('{"type":"noop","params":{}}');

function toHex(bytes: Uint8Array): string {
  let out = '';
  for (const b of bytes) out += b.toString(16).padStart(2, '0');
  return out;
}

// Chain-authoritative digests (see fixture table in the batch spec).
const M_LEGACY = '439f9476f5235ef8637cd837382df24fc2dcb0b33261830e11e1467ed6600433';
const M_USER_BOUND = 'b2fbf42acd0f24909cf7c3905d4a1b8503806b2f42c8bec22d9caacd70531e82';

describe.skipIf(!wasmBuilt)('multi-sig inner digest', () => {
  it('user-bound inner digest matches the chain pin', async () => {
    const { multiSigInnerDigest } = await import('../src/native/multisig.js');
    const digest = await multiSigInnerDigest(USER, BLOB, NONCE, CHAIN_ID);
    expect(toHex(digest)).toBe(M_USER_BOUND);
  });

  it('legacy inner digest matches the chain pin', async () => {
    const { multiSigInnerDigestLegacy } = await import('../src/native/multisig.js');
    const digest = await multiSigInnerDigestLegacy(BLOB, NONCE, CHAIN_ID);
    expect(toHex(digest)).toBe(M_LEGACY);
  });

  it('the two schemes produce distinct digests (user binding is real)', async () => {
    const { multiSigInnerDigest, multiSigInnerDigestLegacy } = await import(
      '../src/native/multisig.js'
    );
    const bound = await multiSigInnerDigest(USER, BLOB, NONCE, CHAIN_ID);
    const legacy = await multiSigInnerDigestLegacy(BLOB, NONCE, CHAIN_ID);
    expect(toHex(bound)).not.toBe(toHex(legacy));
  });

  it('binds the acting account: a different user changes the digest', async () => {
    const { multiSigInnerDigest } = await import('../src/native/multisig.js');
    const a = await multiSigInnerDigest(USER, BLOB, NONCE, CHAIN_ID);
    const b = await multiSigInnerDigest(
      '0x3333333333333333333333333333333333333333',
      BLOB,
      NONCE,
      CHAIN_ID,
    );
    expect(toHex(a)).not.toBe(toHex(b));
  });

  it('sign → recover round-trips on both schemes', async () => {
    const { signMultiSigInner, recoverMultiSigInner } = await import(
      '../src/native/multisig.js'
    );
    const { deriveAddressFromPubkey } = await import('../src/wallet/wasm.js');
    const privKey = new Uint8Array(32).fill(0x42);
    // Derive the expected signer address from the key via a throwaway recover.
    for (const scheme of ['user-bound', 'legacy'] as const) {
      const sig = await signMultiSigInner(privKey, USER, BLOB, NONCE, {
        scheme,
        chainId: CHAIN_ID,
      });
      expect(sig.startsWith('0x')).toBe(true);
      expect(sig.length).toBe(2 + 130); // 0x + 65 bytes
      const recovered = await recoverMultiSigInner(sig, USER, BLOB, NONCE, {
        scheme,
        chainId: CHAIN_ID,
      });
      expect(recovered.startsWith('0x')).toBe(true);
      expect(recovered.length).toBe(42);
      void deriveAddressFromPubkey;
    }
  });

  it('user-bound is the default scheme (no explicit scheme => user-bound)', async () => {
    const { signMultiSigInner, recoverMultiSigInner, multiSigInnerDigest } =
      await import('../src/native/multisig.js');
    const privKey = new Uint8Array(32).fill(0x42);
    const sigDefault = await signMultiSigInner(privKey, USER, BLOB, NONCE, {
      chainId: CHAIN_ID,
    });
    const sigBound = await signMultiSigInner(privKey, USER, BLOB, NONCE, {
      scheme: 'user-bound',
      chainId: CHAIN_ID,
    });
    expect(sigDefault).toBe(sigBound);
    // And it verifies against the user-bound digest.
    const signer = await recoverMultiSigInner(sigDefault, USER, BLOB, NONCE, {
      chainId: CHAIN_ID,
    });
    const digest = await multiSigInnerDigest(USER, BLOB, NONCE, CHAIN_ID);
    expect(digest.length).toBe(32);
    expect(signer.length).toBe(42);
  });
});

describe.skipIf(!wasmBuilt)('multi_sig outer typed wrapper', () => {
  it('encodeType matches the frozen chain type string', async () => {
    const { encodeType } = await import('../src/native/typed.js');
    expect(encodeType('multi_sig')).toBe(
      'MetaFluxTransaction:MultiSig(string metafluxChain,address user,bytes innerActionBlob,bytes[] signatures,uint64 nonce)',
    );
  });

  it('builds a wrapper action JSON with 0x-hex blob + signatures array', async () => {
    const { buildTyped } = await import('../src/native/typed.js');
    const blobHex = `0x${toHex(BLOB)}`;
    const sigs = [`0x${'ab'.repeat(65)}`, `0x${'cd'.repeat(65)}`];
    const built = buildTyped(
      'multi_sig',
      { user: USER, inner_action_blob: blobHex, signatures: sigs },
      NONCE,
      CHAIN_ID,
    );
    const parsed = JSON.parse(built.actionJson) as {
      type: string;
      params: {
        user: string;
        inner_action_blob: string;
        signatures: string[];
        nonce: number;
      };
    };
    expect(parsed.type).toBe('multi_sig');
    expect(parsed.params.user).toBe(USER);
    expect(parsed.params.inner_action_blob).toBe(blobHex);
    expect(parsed.params.signatures).toEqual(sigs);
    // The wrapper nonce is REQUIRED inside params — the node's `NativeMultiSig`
    // has no `#[serde(default)]` for it, so a missing `params.nonce` is a 400 at
    // ingress. Must equal the envelope nonce.
    expect(parsed.params.nonce).toBe(Number(NONCE));
    // Wrapper defaults to no expiry (byte-identical outer envelope).
    expect(built.expiresAfter).toBe(0n);
  });

  it('outer wrapper digest matches the chain pin (plain + expiry)', async () => {
    const { buildTyped, typedActionDigest, signTypedAction, recoverTypedSigner } =
      await import('../src/native/typed.js');
    const blobHex = `0x${toHex(BLOB)}`;
    // The exact fixture-gen signatures: r||s||v with the given fill bytes.
    const sigA = `0x${'11'.repeat(32)}${'22'.repeat(32)}1b`;
    const sigB = `0x${'33'.repeat(32)}${'44'.repeat(32)}1c`;
    const payload = {
      user: USER,
      inner_action_blob: blobHex,
      signatures: [sigA, sigB],
    };
    // O.multisig_outer_digest_plain (chain-generated).
    const plain = await typedActionDigest(buildTyped('multi_sig', payload, NONCE, CHAIN_ID));
    expect(toHex(plain)).toBe(
      'f5ea6e0bb193d12e7c74c0ed1efe06d84da404c087836e1801c565530e29027b',
    );
    // O.multisig_outer_digest_expiry (chain-generated, expiresAfter set).
    const withExpiry = await typedActionDigest(
      buildTyped('multi_sig', payload, NONCE, CHAIN_ID, undefined, 1_735_693_200_000n),
    );
    expect(toHex(withExpiry)).toBe(
      '54e5f5d4fe4f8bf2767539fd0d88ab4d5ed0ecae1ccdd604a8c984016227561c',
    );
    // And a sign → recover round-trip over the outer envelope.
    const privKey = new Uint8Array(32).fill(0x42);
    const signed = await signTypedAction(privKey, 'multi_sig', payload, NONCE, CHAIN_ID);
    expect(signed.signature.length).toBe(2 + 130);
    const recovered = await recoverTypedSigner(signed, 'multi_sig', payload, CHAIN_ID);
    expect(recovered.startsWith('0x')).toBe(true);
    expect(recovered.length).toBe(42);
  });
});
